resources:
  repositories:
  - repository: Cloud_AWS_Templates
    type: git
    ref: refs/heads/trunk
    name: Cloud_AWS_Templates

trigger:
  branches:
    include:
      - trunk
  paths:
    include:
      - fw-eastwest-qa/*
      
variables: 
  project-folder: 's3-bucket'
  cloudformation-template-s3: '$(System.DefaultWorkingDirectory)/$(project-folder)/template-s3.yaml'
  cloudformation-params-s3: '$(System.DefaultWorkingDirectory)/$(project-folder)/params-s3.json'

stages:

# - stage: linterns 
#   displayName: Validations
#   jobs:

 - stage: deploy_dev
   displayName: Deploy DEV
   variables:
   - group: 'infrastructure-security-variables-qa-eastwest-aws'
   - name: stack-name-s3
     value: '$(application-code)-$(project-name)-$(env)-s3-stack'
   - name: stack-name-fw
     value: '$(application-code)-$(project-name)-$(env)-fw-stack'
   - name: env
     value: dev
   - name: buckets3-name
     value: 'us-east-1-secvpc-eastwest-qa'

   jobs:
     
    - template: /aw0000_cloud/templates/job-templates/deployment.yaml@Cloud_AWS_Templates
      parameters:
        account: bancolombia-transit-pdn-aws
        resource: s3
        jobname: s3