resources:
  repositories:
  - repository: demo-david
    type: git
    name: demo-david

trigger:
  branches:
    include:
      - trunk
  paths:
    include:
      - fw-eastwest-qa/*
      
variables: 
  project-folder: 'demo-david'
  cloudformation-template-s3: '$(System.DefaultWorkingDirectory)/$(project-folder)/template-s3.yaml'
  cloudformation-params-s3: '$(System.DefaultWorkingDirectory)/$(project-folder)/params-s3.json'

stages:

# - stage: linterns 
#   displayName: Validations
#   jobs:

 - stage: deploy_dev
   displayName: Deploy DEV
   variables:
   - group: 's3-bucket'
   - name: stack-name-s3
     value: '$(project-name)-$(env)-s3-stack'
   - name: stack-name-fw
     value: '$(application-code)-$(project-name)-$(env)-fw-stack'
   - name: env
     value: pdn

   jobs:
     
    - template: /aw0000_cloud/templates/job-templates/deployment.yaml@demo-david
      parameters:
        account: aws-netdata
        resource: s3
        jobname: s3