apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloworld
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: sauravbrahma/metasploit_image:latest
            command: ["nmap","-T5","-sV","-Pn", "172.17.0.2-20"]
          restartPolicy: Never
