AWSTemplateFormatVersion: 2010-09-09
Description: MyLoadBalancer davidaavilar
Parameters:
  ptestencrypted:
    Type: String
    AllowedValues: 
        - true
        - false
  SourceDBInstanceIdentifier:
    Type: String
  DBInstanceType:
    Type: String
  SourceRegion:
    Type: String
  EnvironmentType:
    Type: String
    Default: qa
    AllowedValues: 
        - qa
        - pdn
Resources:
  MyKey:
    Type: "AWS::KMS::Key"
  MyClassicLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
      Properties:
        AvailabilityZones:
        - "us-east-2a"
        CrossZone: true
        Listeners:
        - InstancePort: '80'
          InstanceProtocol: HTTP
          LoadBalancerPort: '443'
          Protocol: HTTPS
          PolicyNames: 
          - My-SSLNegotiation-Policy
          SSLCertificateId: arn:aws:iam::123456789012:server-certificate/my-server-certificate
        HealthCheck:
          Target: HTTP:80/
          HealthyThreshold: '2'
          UnhealthyThreshold: '3'
          Interval: '10'
          Timeout: '5'
        Policies:
        - PolicyName: My-SSLNegotiation-Policy
          PolicyType: SSLNegotiationPolicyType
          Attributes:
          - Name: Reference-Security-Policy
            Value: ELBSecurityPolicy-TLS-1-2-2017-01
  PanoramaLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties: 
        IpAddressType: ipv4
        Name: "Panorama-LB"
        SubnetMappings: 
          - SubnetId: !Select [ 0, !Ref PublicSubnetIpBlocks ]
          - SubnetId: !Select [ 1, !Ref PublicSubnetIpBlocks ]
        Type: 'network'
  ListenerPanorama1:
    Type: AWS::ElasticLoadBalancingV2::Listener
      Properties: 
        DefaultActions: 
          - Type: 'forward'
            TargetGroupArn: !Ref TargetGroupPanorama1
        LoadBalancerArn: !Ref PanoramaLoadBalancer
        Port: 443
        Protocol: TCP
  TargetGroupPanorama1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties: 
        Name: "Panorama-TG1"
        Port: 443
        Protocol: TCP
        Targets: 
          - Id: !Ref 'Panorama1Instance'
        TargetType: 'instance'
        VpcId: !Ref 'VPC'
