AWSTemplateFormatVersion: '2010-09-09'
Description: Hyperledger Fabric Orderer node resources
Parameters:
  applicationcode:
    Type: String
    Default: nu0094001
  project:
    Type: String
    Default: blockchain
  environment:
    Type: String
    Default: dev
  costcenter:
    Type: String
    Default: C103500281
  pmo:
    Type: String
    Default: PMO31774
  businessservice:
    Type: String
    Default: blockchain
  pImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-04a946859e7d13107
  pInstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t3.micro, t3.2xlarge]
  pDNSRecord:
    Type: String
    ConstraintDescription: Must have a valid domain
  pTopicARN:
    Type: String
    ConstraintDescription: Must be a valid arn
    Default: arn:aws:sns:us-east-1:763669947983:Route53SNS
  pDockerImage:
    Type: String
  pInstanceTagName:
    Type: String
    Default: Orderer
  pLandingZoneStackName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: VPCStackName
  pEmailSubscription:
    Type: String
    Default: crcrios@bancolombia.com.co
  pRoleAcmPcaArn:
    Type: String
    Default: arn:aws:iam::872308410481:role/acm-pca-blockchain-dev
  pArnCertificateAuthority:
    Type: String
    Default: arn:aws:acm-pca:us-east-1:872308410481:certificate-authority/ee2eadae-1a4e-4034-9f22-cc2626854c20
  pCerPkiArn: 
    Description: The ARN of the SNS topic used to request a PKI Certificate. 
    Type: String
Conditions:
  cEnvPdn: !Equals [!Ref environment, pdn]
Resources:
  #-----------------------------LAUNCH CONFIGURATION-----------------
  rLaunchTemplate:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref pImageId
      InstanceType: !Ref pInstanceType
      IamInstanceProfile: !Sub '{{resolve:ssm:/${applicationcode}-${project}-${environment}-arn/orderer_instance_profile:1}}'
      SecurityGroups:
        - !Sub '{{resolve:ssm:/${applicationcode}-${project}-${environment}-arn/orderer_security_group:1}}'
      AssociatePublicIpAddress: true
  rSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref pEmailSubscription
          Protocol: email
      TopicName: !Join
        - '-'
        - - !Ref applicationcode
          - !Ref project
          - !Ref environment
          - !Ref pInstanceTagName

  #-------------------------------AUTOSCALING GROUP------------------
  rAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      LaunchConfigurationName: !Ref rLaunchTemplate
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${pLandingZoneStackName}-PublicSubnet1ID
        - Fn::ImportValue: !Sub ${pLandingZoneStackName}-PublicSubnet2ID
        - Fn::If:
            - cEnvPdn
            - Fn::ImportValue: !Sub ${pLandingZoneStackName}-PublicSubnet3ID
            - Ref: AWS::NoValue
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref applicationcode
              - !Ref project
              - !Ref environment
              - !Ref pInstanceTagName
          PropagateAtLaunch: true
