AWSTemplateFormatVersion: '2010-09-09'
Description: 'Example'
Resources:
### DeveloperRole DevAccount
  almBridgeMQPolicieDeveloperRole:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: almBridgeMQPolicieDeveloperRole
      Roles:
      - eksrole-alm
      - BCO-DevOpsEngineerRole
      - ReadOnly
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          -
            Effect: Allow
            Action:
            - 'iam'
            Resource:
            - "*"
          - 
            Effect: Allow
            Action:
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:GetSecretValue'
            Resource: 
            - "*"
  
