AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket davidaavilar
Parameters:
  BucketName:
    Description: Nombre del Bucket
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls       : True
        BlockPublicPolicy     : True
        IgnorePublicAcls      : True
        RestrictPublicBuckets : True