AWSTemplateFormatVersion: 2010-09-09
Description: RDS davidaavilar
Parameters:
  ptestencrypted:
    Type: String
    AllowedValues: 
        - true
        - false
  SourceDBInstanceIdentifier:
    Type: String
  DBInstanceType:
    Type: String
  SourceRegion:
    Type: String
  EnvironmentType:
    Type: String
    Default: qa
    AllowedValues: 
        - qa
        - pdn
Mappings:
  StorageEncrypted:
    qa: 
      value: false
    pdn:
      value: true
Resources:
  MyKey:
    Type: "AWS::KMS::Key"
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "kms:*"
            Resource: "*"
  MyDBSmall:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: !Ref DBInstanceType
      SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifier
      SourceRegion: !Ref SourceRegion
      KmsKeyId: !Ref MyKey
#      StorageEncrypted: !FindInMap [StorageEncrypted, !Ref EnvironmentType, value]
#      StorageEncrypted: !Ref ptestencrypted
      StorageEncrypted: false
      Tags: 
        - Key: "Name"
          Value: "pruebacft"
